config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.htmlRails.application.routes.draw do
Rails.application.routes.draw do
  get "about_renamed", to: "about#index", as: :about # the _path will return this route, even if the url name gets changed == # get "about", to: "about#index"

  # User registration and control
  get "sign_up", to: "user#new" # Form to sign up
  post "sign_up", to: "user#create" # Submit form
  get "user", to: "user#show", as: :user_profile
  delete "user", to: "user#delete", as: :delete_user
  # Session management
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  # Updating a user's password
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"
  # Resetting a user's password via email and globalID token
  get "password/reset", to: "passwords_resets#new"
  post "password/reset", to: "passwords_resets#create"
  get "password/reset/edit", to: "passwords_resets#edit"
  patch "password/reset/edit", to: "passwords_resets#update"

  get "/", to: "main#index", as: :root # Same as root to: "" || root ""

  namespace :admin do
    get "dashboard", to: "admin#dashboard", as: "dashboard"
    patch "users/:id/toggle_admin", to: "admin#toggle_admin", as: "toggle_admin"
  end

  resources :projects # This will create all the routes for the projects controller
end

app/views/shared/_flash.html.erb
<!-- generalized flash message handling -->
<% flash.each do |key, message| %>
    <!-- possible to add extra displaytype definitions if, for example, you would want to display -info messages (blue) in some cases -->
    <% display_type = key == 'alert' ? 'danger' : 'success' %>
    <div class="alert alert-<%= display_type %> mt-4". role="alert">
    <%= message %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg shadow-sm" style="background: linear-gradient(to right, #2196F3, #64B5F6);">
  <div class="container">
    <!-- Brand Name -->
    <%= link_to "MyApp", root_path, class: "navbar-brand text-white fw-bold fs-4" %>

    <!-- Mobile Toggle Button -->
    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar Links -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link text-white fw-semibold px-3" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link text-white fw-semibold px-3" %>
        </li>
      </ul>

      <!-- Right-Aligned Links -->
      <ul class="navbar-nav ms-auto">
        <% if Current.user %>
          <% if Current.user.is_admin %>
            <li class="nav-item">
              <%= link_to "Admin Panel", admin_dashboard_path, class: "nav-link text-warning fw-semibold px-3" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Projects", projects_path, class: "nav-link text-white fw-semibold px-3" %>
          </li>
          <li class="nav-item">
            <%= link_to Current.user.email, user_profile_path, class: "nav-link text-white fw-semibold px-3" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-light fw-semibold px-3 mx-2" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class: "nav-link text-white fw-semibold px-3" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "btn btn-outline-light fw-semibold px-3 mx-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>